FROM golang:1.23-alpine3.20 AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
ENV CGO_ENABLED=0
RUN go build -trimpath -ldflags="-s -w" -o /app/api ./main.go

FROM alpine:3.20
WORKDIR /app
RUN apk add --no-cache ca-certificates
COPY --from=build --chmod=755 /app/api /app/api
ENV PORT=8080
EXPOSE 8080
ENTRYPOINT ["/app/api"]
